// <auto-generated />
using System;
using BabyFeedingRecordWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BabyFeedingRecordWebApplication.Migrations
{
    [DbContext(typeof(BabyFeedingRecordWebApplicationContext))]
    [Migration("20221123102840_AddBabyFoodModel")]
    partial class AddBabyFoodModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BabyFeedingRecordWebApplication.Models.BabyFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BabyFood");
                });

            modelBuilder.Entity("BabyFeedingRecordWebApplication.Models.FeedingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BabyFoodVolume")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FeedingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormularMilkVolume")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MotherMilkVolume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeedingRecord");
                });

            modelBuilder.Entity("BabyFeedingRecordWebApplication.Models.FeedingStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("FeedingTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("FormularMilkPercentage")
                        .HasColumnType("float");

                    b.Property<int>("FormularMilkTotal")
                        .HasColumnType("int");

                    b.Property<double>("MotherMilkPercentage")
                        .HasColumnType("float");

                    b.Property<int>("MotherMilkTotal")
                        .HasColumnType("int");

                    b.Property<double>("TimeIntervalAvg")
                        .HasColumnType("float");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeedingStatistics");
                });

            modelBuilder.Entity("BabyFeedingRecordWebApplication.Models.MovingAvg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Mnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MovingAvg");
                });
#pragma warning restore 612, 618
        }
    }
}
